limit: 3
line: qn
streamers:
  KZjd4KQZzRQ.webm:
    copyright: 2
    cover: KZjd4KQZzRQ.jpg
    desc: "https://www.youtube.com/watch?v=KZjd4KQZzRQ"
    desc_format_id: 0
    dolby: 0
    dynamic: ''
    open_subtitle: false
    source: https://www.youtube.com/watch?v=KZjd4KQZzRQ
    subtitle:
      lan: ''
      open: 0
    tag: "youtube"
    tid: 209
    title: Use FACES to Cut Objects in SketchUp - Curic Face Knife and Lattice Maker!
streamers:
  LworFjKlr7g.webm:
    copyright: 2
    cover: LworFjKlr7g.jpg
    desc: "https://www.youtube.com/watch?v=LworFjKlr7g"
    desc_format_id: 0
    dolby: 0
    dynamic: ''
    open_subtitle: false
    source: https://www.youtube.com/watch?v=LworFjKlr7g
    subtitle:
      lan: ''
      open: 0
    tag: "youtube"
    tid: 209
    title: RANDOM Extrusion and Movement in SketchUp!!
